name: Auto-merge Dependabot PRs
on:
     pull_request:
       types: [opened, synchronized]
       branches:
         - '*'
jobs:
     automerge:
       runs-on: ubuntu-latest
       steps:
         - name: Automerge Dependabot PRs
           uses: actions/github-script@v6
           env:
             PR_URL: ${{ github.event.pull_request.html_url }}
           with:
             github_token: ${{ secrets.GITHUB_TOKEN }}
             script: |
               github.rest.pulls.merge({
                 pull_number: ${{ github.event.pull_request.number }},
                 merge_method: 'merge'
               })
